In [2]:
# Import required libraries
import pandas as pd
import numpy as np

In [3]:
# Load dataset
df = pd.read_excel('student_data.xlsx')

# Show all columns when displaying DataFrames
pd.set_option('display.max_columns', None)
df.head()

,student_id,course,student_cohort,academic_status,failed_subjects,study_skills(attended),referral,pp_meeting,self_assessment,readiness_assessment_results,follow_up,follow_up_type,subject_1,subject_1_assess_1,subject_1_assess_2,subject_1_assess_3,subject_1_assess_4,attendance_1,learn_jcu_issues_1,lecturer_referral_1,subject_2,subject_2_assess_1,subject_2_assess_2,subject_2_assess_3,subject_2_assess_4,attendance_2,learn_jcu_issues_2,lecturer_referral_2,subject_3,subject_3_assess_1,subject_3_assess_2,subject_3_assess_3,subject_4_assess_4,attendance_3,learn_jcu_issues_3,lecturer_referral_3,comments,identified_issues
0,1,Master of Business Administration,SRI to JCUB,At Risk,NaN,Essential Skills,Student Counsellor,Booked,Yes,L/G:9/10 N:5/10 R:8/10,Yes,No Reply,NaN,7.70,27.22,26.51,50.09,20,Access,Concern for Welfare,NaN,69.33,44.44,11.39,18.78,41,Access,Attendance,NaN,39.02,17.71,94.50,9.83,89,Access,Non Submission,Week 8. Student re-engaged with tutorials. Sub...,Late Enrollment
1,2,Master of Business Administration,Continuing,Excluded,NaN,Referencing,Student Advocate,Not relevant,Yes,L/G:9/10 N:5/10 R:8/10,No,Phone,NaN,31.14,54.66,81.72,1.96,9,Access,Non Submission,NaN,95.23,48.61,14.68,44.77,66,No Access,Concern for Welfare,NaN,3.72,38.52,25.80,11.80,100,No Access,Non Submission,booked to see a doctor. Week 5. Student contac...,Poor time management
2,3,Master of Business Administration,First year,At Risk,NaN,Writing,Enrollment,Attended,Yes,L/G:9/10 N:5/10 R:8/10,Yes,Phone,NaN,39.09,75.39,84.62,82.66,51,No Access,Attendance,NaN,86.20,98.80,71.57,96.08,64,No Access,Concern for Welfare,NaN,77.77,77.27,81.95,62.35,42,Access,Attendance,Week 8. Student re-engaged with tutorials. Sub...,Poor time management
3,4,Master of Business Administration,New,Excluded,NaN,Essential Skills,Student Advocate,Attended,No,L/G:9/10 N:5/10 R:8/10,No,F2F,NaN,88.59,84.36,3.79,26.05,34,Access,Concern for Welfare,NaN,7.69,25.96,49.83,17.77,57,Access,Non Submission,NaN,95.41,8.93,3.21,99.15,51,Access,Concern for Welfare,Week 6. Student submitted assessment late. Ext...,Death in family
4,5,Master of Business Administration,Continuing,At Risk,NaN,Essential Skills and Reading,Student Counsellor,Not relevant,No,L/G:9/10 N:5/10 R:8/10,Yes,No Reply,NaN,0.98,13.80,53.40,39.69,45,Access,Attendance,NaN,60.51,57.47,15.80,33.59,3,No Access,Concern for Welfare,NaN,90.12,52.18,36.05,20.65,19,Access,Concern for Welfare,Week 3 late enrolment. Student finding it diff...,Sickness

#### Data Cleaning and Exploration

In [4]:
# Print a concise summary of the DataFrame, including column names, data types, non-null counts, and memory usage.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 698 entries, 0 to 697
Data columns (total 38 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   student_id                    698 non-null    int64
 1   course                        698 non-null    object
 2   student_cohort                698 non-null    object
 3   academic_status               698 non-null    object
 4   failed_subjects               0 non-null      float64
 5   study_skills(attended)        698 non-null    object
 6   referral                      698 non-null    object
 7   pp_meeting                    698 non-null    object
 8   self_assessment               698 non-null    object
 9   readiness_assessment_results  698 non-null    object
 10  follow_up                     698 non-null    object
 11  follow_up_type                698 non-null    object
 12  subject_1                     0 non-null      float64
 13  subject_1_assess_1            698 non-null    float64
 14  subject_1_assess_2            698 non-null    float64
 15  subject_1_assess_3            698 non-null    float64
 16  subject_1_assess_4            698 non-null    float64
 17  attendance_1                  698 non-null    int64
 18  learn_jcu_issues_1            698 non-null    object
 19  lecturer_referral_1           698 non-null    object
 20  subject_2                     0 non-null      float64
 21  subject_2_assess_1            698 non-null    float64
 22  subject_2_assess_2            698 non-null    float64
 23  subject_2_assess_3            698 non-null    float64
 24  subject_2_assess_4            698 non-null    float64
 25  attendance_2                  698 non-null    int64
 26  learn_jcu_issues_2            698 non-null    object
 27  lecturer_referral_2           698 non-null    object
 28  subject_3                     0 non-null      float64
 29  subject_3_assess_1            698 non-null    float64
 30  subject_3_assess_2            698 non-null    float64
 31  subject_3_assess_3            698 non-null    float64
 32  subject_4_assess_4            698 non-null    float64
 33  attendance_3                  698 non-null    int64
 34  learn_jcu_issues_3            698 non-null    object
 35  lecturer_referral_3           698 non-null    object
 36  comments                      698 non-null    object
 37  identified_issues             698 non-null    object
dtypes: float64(16), int64(4), object(18)
memory usage: 207.3+ KB

In [5]:
df.rename(columns={'subject_4_assess_4':'subject_3_assess_4'}, inplace=True)
df.columns

Index(['student_id', 'course', 'student_cohort', 'academic_status',
       'failed_subjects', 'study_skills(attended)', 'referral', 'pp_meeting',
       'self_assessment', 'readiness_assessment_results', 'follow_up',
       'follow_up_type', 'subject_1', 'subject_1_assess_1',
       'subject_1_assess_2', 'subject_1_assess_3', 'subject_1_assess_4',
       'attendance_1', 'learn_jcu_issues_1', 'lecturer_referral_1',
       'subject_2', 'subject_2_assess_1', 'subject_2_assess_2',
       'subject_2_assess_3', 'subject_2_assess_4', 'attendance_2',
       'learn_jcu_issues_2', 'lecturer_referral_2', 'subject_3',
       'subject_3_assess_1', 'subject_3_assess_2', 'subject_3_assess_3',
       'subject_3_assess_4', 'attendance_3', 'learn_jcu_issues_3',
       'lecturer_referral_3', 'comments', 'identified_issues'],
      dtype='object')

In [6]:
df['course'] = df['course'].str.strip().str.lower()
df['course'].unique()

array(['master of business administration',
       'master of education - master of business administration',
       'master of information technology', 'bachelor of business',
       'master of engineering management',
       'bachelor of information technology',
       'master of professional accounting',
       'master of international tourism and hospitality management',
       'bachelor of tourism, hospitality and events',
       'master of professional account and master of business administration',
       'bachelor of commerce',
       'master of international tourism and hospitality management - master of business administration',
       'master of data science (professional)',
       'master of information technology - master of business administration',
       'postgraduate qualifying program - business'], dtype=object)

In [7]:
# Map subject code to subject names using Dictionary
subject_dict = {
    "BU1002": "Accounting for Decision Making",
    "BU1003": "Principles of Economics",
    "BU1007": "Principles of Data Analysis for Business",
    "BU1112": "Business Law",
    "BX2011": "Foundation of Accounting Principles",
    "BX2014": "Principles of Finance",
    "CP1401": "Fundamentals of Problem Solving and Programming I",
    "CP1402": "Internet Fundamentals",
    "CP1404": "Programming II",
    "TO1008": "Introduction to Tourism, Hospitality and Events Management",
    "TO2117": "Food and Beverage Management",
    "TO3052": "Experience Design for Tourism Hospitality and Events",
    "LB5113": "Corporate Strategy",
    "LB5202": "Marketing Essentials",
    "LB5205": "People in Organisations",
    "MA5831": "Advanced Data Management and Analysis using SAS",
    "MA5840": "Data Science and Strategic Decision Making for Business",
    "MA5851": "Data Science Master Class 1",
    "ED5097": "Research Design and Proposal",
    "ED5880": "Educational Leadership",
    "EG5200": "Career Planning",
    "EG5220": "Advanced Asset Management and Reliability",
    "EG5310": "Professional Placement",
    "CP5046": "ICT Project 1: Analysis and Design",
    "CP5047": "ICT Project 2: Implementation and Commissioning",
    "CP5503": "Enterprise Database Systems - Oracle",
    "TO5101": "Tourism Systems Analysis",
    "TO5103": "Global Destinations and Competitiveness",
    "TO5104": "Tourist Management Strategies",
    "CO5117": "Introduction to Accounting",
    "CO5103": "Management Accounting",
    "CO5109": "Corporate Finance",
    "LB5203": "Sustainable Enterprise",
    "LB5212": "Accounting and Finance for Managers"
}

In [8]:
# Get the subject name from the subject code
subject_dict['BU1007'] # Output: Principles of Data Analysis for Business

'Principles of Data Analysis for Business'

In [9]:
# Map each course to a list of three subject codes
course_subjects = {
    'Bachelor of Business': ['BU1002', 'BU1003', 'BU1007'],
    'Bachelor of Commerce': ['BU1112', 'BX2011', 'BX2014'],
    'Bachelor of Information Technology': ['CP1401', 'CP1402', 'CP1404'],
    'Bachelor of Tourism, Hospitality and Events': ['TO1008', 'TO2117', 'TO3052'],
    'Master of Business Administration': ['LB5113', 'LB5202', 'LB5205'],
    'Master of Data Science (Professional)': ['MA5831', 'MA5840', 'MA5851'],
    'Master of Education - Master of Business Administration': ['ED5097', 'ED5880', 'LB5113'],
    'Master of Engineering Management': ['EG5200', 'EG5220', 'EG5310'],
    'Master of Information Technology': ['CP5046', 'CP5047', 'CP5503'],
    'Master of Information Technology - Master of Business Administration': ['CP5046', 'LB5113', 'LB5202'],
    'Master of International Tourism and Hospitality Management': ['TO5101', 'TO5103', 'TO5104'],
    'Master of International Tourism and Hospitality Management - Master of Business Administration': ['TO5101', 'LB5113', 'LB5202'],
    'Master of Professional Accounting': ['CO5117', 'CO5103', 'CO5109'],
    'Master of Professional Accounting - Master of Business Administration': ['CO5117', 'CO5103', 'LB5113'],
    'Postgraduate Qualifying Program - Business': ['LB5202', 'LB5203', 'LB5212']
}

In [10]:
# Get the course subjects from the course
course_subjects['Bachelor of Information Technology'] # Output: 'CP1401', 'CP1402', 'CP1404']

['CP1401', 'CP1402', 'CP1404']

In [11]:
# Create a new dictionary with cleaned course names as keys
# For each key-value pair in the original course_subjects dictionary:
#   Remove any leading/trailing spaces from the course name (key) using strip()
#   Convert the course name to lowercase using lower()
#   Keep the value (list of subjects) unchanged
cleaned_course_subjects = {k.strip().lower(): v for k, v in course_subjects.items()}
cleaned_course_subjects

{'bachelor of business': ['BU1002', 'BU1003', 'BU1007'],
 'bachelor of commerce': ['BU1112', 'BX2011', 'BX2014'],
 'bachelor of information technology': ['CP1401', 'CP1402', 'CP1404'],
 'bachelor of tourism, hospitality and events': ['TO1008', 'TO2117', 'TO3052'],
 'master of business administration': ['LB5113', 'LB5202', 'LB5205'],
 'master of data science (professional)': ['MA5831', 'MA5840', 'MA5851'],
 'master of education - master of business administration': ['ED5097',
  'ED5880',
  'LB5113'],
 'master of engineering management': ['EG5200', 'EG5220', 'EG5310'],
 'master of information technology': ['CP5046', 'CP5047', 'CP5503'],
 'master of information technology - master of business administration': ['CP5046',
  'LB5113',
  'LB5202'],
 'master of international tourism and hospitality management': ['TO5101',
  'TO5103',
  'TO5104'],
 'master of international tourism and hospitality management - master of business administration': ['TO5101',
  'LB5113',
  'LB5202'],
 'master of professional accounting': ['CO5117', 'CO5103', 'CO5109'],
 'master of professional accounting - master of business administration': ['CO5117',
  'CO5103',
  'LB5113'],
 'postgraduate qualifying program - business': ['LB5202', 'LB5203', 'LB5212']}

In [12]:
# Get unique course names in DataFrame
unique_courses = df['course'].unique()

# Find which course names are not keys in cleaned_course_subjects dictionary
courses_not_in_cleaned = [course for course in unique_courses if course not in cleaned_course_subjects]
courses_not_in_cleaned

['master of professional account and master of business administration']

In [13]:
df['course'].replace('master of professional account and master of business administration', 'master of professional accounting - master of business administration', inplace=True)

/tmp/ipykernel_83451/155377907.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['course'].replace('master of professional account and master of business administration', 'master of professional accounting - master of business administration', inplace=True)

In [14]:
# check if the course value has been updated
df['course'].unique()

array(['master of business administration',
       'master of education - master of business administration',
       'master of information technology', 'bachelor of business',
       'master of engineering management',
       'bachelor of information technology',
       'master of professional accounting',
       'master of international tourism and hospitality management',
       'bachelor of tourism, hospitality and events',
       'master of professional accounting - master of business administration',
       'bachelor of commerce',
       'master of international tourism and hospitality management - master of business administration',
       'master of data science (professional)',
       'master of information technology - master of business administration',
       'postgraduate qualifying program - business'], dtype=object)

In [15]:
# Assigns subject codes to each student based on their course.
# For each row, looks up the course in the cleaned_course_subjects dictionary.
# If the course is found, fills subject_1, subject_2, and subject_3 with the corresponding subject codes.
# If the course is not found, fills these columns with None.
def assign_subjects(row):
    subjects = cleaned_course_subjects.get(row['course'], [None, None, None])
    row['subject_1'], row['subject_2'], row['subject_3'] = subjects
    return row

df = df.apply(assign_subjects, axis=1)

In [16]:
# Check for null values in subject 1 to 3
df[['subject_1', 'subject_2', 'subject_3']].isnull().sum()

subject_1    0
subject_2    0
subject_3    0
dtype: int64

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 698 entries, 0 to 697
Data columns (total 38 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   student_id                    698 non-null    int64
 1   course                        698 non-null    object
 2   student_cohort                698 non-null    object
 3   academic_status               698 non-null    object
 4   failed_subjects               0 non-null      float64
 5   study_skills(attended)        698 non-null    object
 6   referral                      698 non-null    object
 7   pp_meeting                    698 non-null    object
 8   self_assessment               698 non-null    object
 9   readiness_assessment_results  698 non-null    object
 10  follow_up                     698 non-null    object
 11  follow_up_type                698 non-null    object
 12  subject_1                     698 non-null    object
 13  subject_1_assess_1            698 non-null    float64
 14  subject_1_assess_2            698 non-null    float64
 15  subject_1_assess_3            698 non-null    float64
 16  subject_1_assess_4            698 non-null    float64
 17  attendance_1                  698 non-null    int64
 18  learn_jcu_issues_1            698 non-null    object
 19  lecturer_referral_1           698 non-null    object
 20  subject_2                     698 non-null    object
 21  subject_2_assess_1            698 non-null    float64
 22  subject_2_assess_2            698 non-null    float64
 23  subject_2_assess_3            698 non-null    float64
 24  subject_2_assess_4            698 non-null    float64
 25  attendance_2                  698 non-null    int64
 26  learn_jcu_issues_2            698 non-null    object
 27  lecturer_referral_2           698 non-null    object
 28  subject_3                     698 non-null    object
 29  subject_3_assess_1            698 non-null    float64
 30  subject_3_assess_2            698 non-null    float64
 31  subject_3_assess_3            698 non-null    float64
 32  subject_3_assess_4            698 non-null    float64
 33  attendance_3                  698 non-null    int64
 34  learn_jcu_issues_3            698 non-null    object
 35  lecturer_referral_3           698 non-null    object
 36  comments                      698 non-null    object
 37  identified_issues             698 non-null    object
dtypes: float64(13), int64(4), object(21)
memory usage: 207.3+ KB

In [18]:
df['course'].value_counts()

course
master of business administration                                                                 102
master of education - master of business administration                                            90
master of information technology                                                                   77
bachelor of business                                                                               71
master of engineering management                                                                   69
bachelor of information technology                                                                 56
master of professional accounting                                                                  55
master of international tourism and hospitality management                                         50
bachelor of tourism, hospitality and events                                                        30
master of professional accounting - master of business administration                              24
bachelor of commerce                                                                               22
master of international tourism and hospitality management - master of business administration     21
master of data science (professional)                                                              13
master of information technology - master of business administration                               11
postgraduate qualifying program - business                                                          7
Name: count, dtype: int64

In [19]:
df.head()

,student_id,course,student_cohort,academic_status,failed_subjects,study_skills(attended),referral,pp_meeting,self_assessment,readiness_assessment_results,follow_up,follow_up_type,subject_1,subject_1_assess_1,subject_1_assess_2,subject_1_assess_3,subject_1_assess_4,attendance_1,learn_jcu_issues_1,lecturer_referral_1,subject_2,subject_2_assess_1,subject_2_assess_2,subject_2_assess_3,subject_2_assess_4,attendance_2,learn_jcu_issues_2,lecturer_referral_2,subject_3,subject_3_assess_1,subject_3_assess_2,subject_3_assess_3,subject_3_assess_4,attendance_3,learn_jcu_issues_3,lecturer_referral_3,comments,identified_issues
0,1,master of business administration,SRI to JCUB,At Risk,NaN,Essential Skills,Student Counsellor,Booked,Yes,L/G:9/10 N:5/10 R:8/10,Yes,No Reply,LB5113,7.70,27.22,26.51,50.09,20,Access,Concern for Welfare,LB5202,69.33,44.44,11.39,18.78,41,Access,Attendance,LB5205,39.02,17.71,94.50,9.83,89,Access,Non Submission,Week 8. Student re-engaged with tutorials. Sub...,Late Enrollment
1,2,master of business administration,Continuing,Excluded,NaN,Referencing,Student Advocate,Not relevant,Yes,L/G:9/10 N:5/10 R:8/10,No,Phone,LB5113,31.14,54.66,81.72,1.96,9,Access,Non Submission,LB5202,95.23,48.61,14.68,44.77,66,No Access,Concern for Welfare,LB5205,3.72,38.52,25.80,11.80,100,No Access,Non Submission,booked to see a doctor. Week 5. Student contac...,Poor time management
2,3,master of business administration,First year,At Risk,NaN,Writing,Enrollment,Attended,Yes,L/G:9/10 N:5/10 R:8/10,Yes,Phone,LB5113,39.09,75.39,84.62,82.66,51,No Access,Attendance,LB5202,86.20,98.80,71.57,96.08,64,No Access,Concern for Welfare,LB5205,77.77,77.27,81.95,62.35,42,Access,Attendance,Week 8. Student re-engaged with tutorials. Sub...,Poor time management
3,4,master of business administration,New,Excluded,NaN,Essential Skills,Student Advocate,Attended,No,L/G:9/10 N:5/10 R:8/10,No,F2F,LB5113,88.59,84.36,3.79,26.05,34,Access,Concern for Welfare,LB5202,7.69,25.96,49.83,17.77,57,Access,Non Submission,LB5205,95.41,8.93,3.21,99.15,51,Access,Concern for Welfare,Week 6. Student submitted assessment late. Ext...,Death in family
4,5,master of business administration,Continuing,At Risk,NaN,Essential Skills and Reading,Student Counsellor,Not relevant,No,L/G:9/10 N:5/10 R:8/10,Yes,No Reply,LB5113,0.98,13.80,53.40,39.69,45,Access,Attendance,LB5202,60.51,57.47,15.80,33.59,3,No Access,Concern for Welfare,LB5205,90.12,52.18,36.05,20.65,19,Access,Concern for Welfare,Week 3 late enrolment. Student finding it diff...,Sickness

In [20]:
df['academic_status'].value_counts()

academic_status
Academic Caution    156
At Risk             148
Excluded            133
Conditional         131
Satisfactory        130
Name: count, dtype: int64

###### Clean the academic status column

In [21]:
# Standardize the values (strip whitespace and title case) 
df['academic_status'] = df['academic_status'].str.strip().str.title()

In [22]:
# Shuffle the DataFrame
df = df.sample(frac=1, random_state=42).reset_index(drop=True)
# Define the target distribution
target_counts = {
    'Satisfactory': 524,
    'Academic Caution': 70,
    'Conditional': 99,
    'Excluded': 5
}

In [23]:
# Create a new column with the desired academic status
new_statuses = (
    ['Satisfactory'] * target_counts['Satisfactory'] +
    ['Academic Caution'] * target_counts['Academic Caution'] +
    ['Conditional'] * target_counts['Conditional'] +
    ['Excluded'] * target_counts['Excluded']
)

In [24]:
# Assign to the DataFrame
df['academic_status'] = new_statuses

# Confirm the new distribution
df['academic_status'].value_counts()

academic_status
Satisfactory        524
Conditional          99
Academic Caution     70
Excluded              5
Name: count, dtype: int64

###### Clean the student cohort column

In [25]:
df['student_cohort'].value_counts()

student_cohort
Return to Study    101
First year          93
Transferred         92
Continuing          89
Excluded            86
LOA                 85
New                 78
SRI to JCUB         74
Name: count, dtype: int64

In [26]:
# List of cohort values for which academic status is 'satisfactory
satisfactory_cohorts = ['SRI to JCUB', 'Transferred', 'New']

# Update the academic_status column for those cohorts
df.loc[df['student_cohort'].isin(satisfactory_cohorts), 'academic_status'] = 'Satisfactory'

###### Group Courses into IT and Non IT

In [27]:
# List of courses that falls under course group 'IT'
it_courses = [ 'master of information technology',
    'bachelor of information technology',
    'master of data science (professional)',
    'master of information technology - master of business administration',
]

In [28]:
# Create a new column 'course_group' based on whether the course is in the IT list
df['course_group'] = df['course'].apply(
    lambda x: 'IT' if x in it_courses else 'Non-IT'
)

###### Generate records of failed subjects for the course IT

In [29]:
# Get the row numbers (indices) for each group
it_indices = df[df['course_group']== 'IT'].index

# Subset of IT course
# Check the distribution number of academic status (Course IT) 
it_df = df.loc[it_indices].copy()
it_df['academic_status'].value_counts()

academic_status
Satisfactory        132
Conditional          14
Academic Caution     10
Excluded              1
Name: count, dtype: int64

In [30]:
# Select 6 students from IT students with the academic status 'Satisfactory'
satisfactory_it = it_df[it_df['academic_status'] == 'Satisfactory'].index
# Randomly choose indices to replace
reassign_academic_status = np.random.choice(satisfactory_it, size = 6, replace = False)

In [31]:
# Reassign 6 Students from Satisfactory to Other Academic Statuses
statuses_to_assign = ['Conditional', 'Academic Caution', 'Excluded']
for i, status in enumerate(statuses_to_assign):
    df.loc[reassign_academic_status[i*3:(i+1)*3], 'academic_status'] = status

In [32]:
# Check updated value counts for IT academic status
it_df = df.loc[it_indices].copy()
it_df['academic_status'].value_counts()

academic_status
Satisfactory        126
Conditional          17
Academic Caution     13
Excluded              1
Name: count, dtype: int64

In [33]:
# Assign 0 failed subjects to Satisfactory IT students
satisfactory_mask = it_df['academic_status'] == 'Satisfactory'
it_df.loc[satisfactory_mask, 'failed_subjects'] = 0

# Identify non-Satisfactory (i.e., failed) students
failed_mask = ~satisfactory_mask
failed_it_indices = it_df[failed_mask].index

# Assign >3 failed subjects to 10 students (1 of them should be Excluded)

# First, get the Excluded student
excluded_mask = it_df['academic_status'] == 'Excluded'
excluded_index = it_df[excluded_mask].index

# Assign random failed_subjects = 6–8 to the Excluded student
it_df.loc[excluded_index, 'failed_subjects'] = np.random.randint(6, 9, size=len(excluded_index))

# Now select 9 more students (excluding Excluded) to get 4–5 failed subjects
eligible_for_high_fail = failed_it_indices.difference(excluded_index)

# Now select 9 more students (excluding Excluded) to get 4–5 failed subjects
eligible_for_high_fail = failed_it_indices.difference(excluded_index)

# Select 9 more randomly to total 10 students failing >3 subjects
more_than_3_indices = np.random.choice(eligible_for_high_fail, size=9, replace=False)
it_df.loc[more_than_3_indices, 'failed_subjects'] = np.random.randint(4, 6, size=9)

# STEP 5: Remaining IT failed students — distribute 1–2 failed subjects
remaining_failed = eligible_for_high_fail.difference(more_than_3_indices)

# 21 failed students remaining
# Randomly split into two groups for 1 and 2 failed subjects
n_remain = len(remaining_failed)  # 21
half = n_remain // 2  # 10 or 11

remaining_failed = list(remaining_failed)
np.random.shuffle(remaining_failed)

low_1_fail = remaining_failed[:half]
low_2_fail = remaining_failed[half:]

# Assign 1s and 2s
it_df.loc[low_1_fail, 'failed_subjects'] = 1
it_df.loc[low_2_fail, 'failed_subjects'] = 2

In [34]:
# Update the failed_subjects column in the main data frame df
df.loc[it_df.index, 'failed_subjects'] = it_df['failed_subjects']

In [35]:
# Check only the IT students
it_students = df.loc[it_indices]

# 1. Total IT students who failed (not Satisfactory)
it_failed = it_students[it_students['academic_status'] != 'Satisfactory']

# 2. Total with non-zero failed_subjects
non_zero_fails = it_failed[it_failed['failed_subjects'] > 0]
print("Total assigned failed_subjects to IT failed students:", len(non_zero_fails))  # 31

# 3. Number of students with >3 failed subjects
gt3 = non_zero_fails[non_zero_fails['failed_subjects'] > 3]
print("Number with >3 failed subjects:", len(gt3))  # 10

# 4. Number with <=3 failed subjects
lte3 = non_zero_fails[non_zero_fails['failed_subjects'] <= 3]
print("Number with <=3 failed subjects:", len(lte3))  # 21

# 5. Print failed_subjects distribution (should show a variety like 1, 2, 4, etc.)
print("\nFailed Subjects Distribution:")
print(non_zero_fails['failed_subjects'].value_counts().sort_index())

# 6. Confirm no failed_subjects assigned to Satisfactory students
sat_students = it_students[it_students['academic_status'] == 'Satisfactory']
sats_with_fails = sat_students[sat_students['failed_subjects'] != 0]
print("\nSatisfactory students incorrectly assigned fails:", len(sats_with_fails))  # 0

Total assigned failed_subjects to IT failed students: 31
Number with >3 failed subjects: 10
Number with <=3 failed subjects: 21

Failed Subjects Distribution:
failed_subjects
1.0    10
2.0    11
4.0     6
5.0     3
6.0     1
Name: count, dtype: int64

Satisfactory students incorrectly assigned fails: 0

###### Generate records of failed subjects for the course Non-IT

In [36]:
# Get non-IT indices
nonit_indices = df[df['course_group']== 'Non-IT'].index

# Subset of Non-IT course
# Check the distribution number of academic status (Course Non-IT) 
nonit_df = df.loc[nonit_indices].copy()
nonit_df['academic_status'].value_counts()

academic_status
Satisfactory        458
Conditional          48
Academic Caution     32
Excluded              3
Name: count, dtype: int64

In [37]:
# CONTROL 'Excluded' COUNT TO 5
current_excluded = (nonit_df['academic_status'] == 'Excluded').sum()
desired = 5

if current_excluded > desired:
    # Too many: set some to 'Conditional' or similar
    excluded = nonit_df[nonit_df['academic_status'] == 'Excluded'].index
    to_remove = np.random.choice(excluded, current_excluded - desired, replace=False)
    df.loc[to_remove, 'academic_status'] = 'Conditional'  # or 'Academic Caution'
elif current_excluded < desired:
    # Too few: set some from non-Excluded, non-Satisfactory
    not_excluded = nonit_df[nonit_df['academic_status'] != 'Excluded'].index
    candidates = not_excluded.intersection(nonit_df[nonit_df['academic_status'] != 'Satisfactory'].index)
    to_add = np.random.choice(candidates, desired - current_excluded, replace=False)
    df.loc[to_add, 'academic_status'] = 'Excluded'

In [38]:
# Refresh
nonit_df = df.loc[nonit_indices].copy()
print("After setting exactly 5 'Excluded':")
print(nonit_df['academic_status'].value_counts())

After setting exactly 5 'Excluded':
academic_status
Satisfactory        458
Conditional          48
Academic Caution     30
Excluded              5
Name: count, dtype: int64

In [39]:
# 3. NOW ASSIGN 'Satisfactory' TO NON-EXCLUDED, NON-SATISFACTORY STUDENTS
non_satisfactory = nonit_df['academic_status'] != 'Satisfactory'
non_excluded = nonit_df['academic_status'] != 'Excluded'
eligible = nonit_df[non_satisfactory & non_excluded].index

reassign_academic_status = np.random.choice(eligible, min(37, len(eligible)), replace=False)
df.loc[reassign_academic_status, 'academic_status'] = 'Satisfactory'

# Final counts
nonit_df = df.loc[nonit_indices].copy()
print("Final:")
print(nonit_df['academic_status'].value_counts())

Final:
academic_status
Satisfactory        495
Conditional          25
Academic Caution     16
Excluded              5
Name: count, dtype: int64

In [40]:
# Assign 0 failed subjects to Satisfactory Non IT students
satisfactory_mask = nonit_df['academic_status'] == 'Satisfactory'
nonit_df.loc[satisfactory_mask, 'failed_subjects'] = 0

# Identify non-Satisfactory (i.e., failed) students
failed_mask = ~satisfactory_mask
failed_nonit_indices = nonit_df[failed_mask].index

# Assign >3 failed subjects to 7 students (5 of them should be Excluded)

# First, get the Excluded student
excluded_mask = nonit_df['academic_status'] == 'Excluded'
excluded_index = nonit_df[excluded_mask].index

# Assign random failed_subjects = 6–8 to the Excluded student
nonit_df.loc[excluded_index, 'failed_subjects'] = np.random.randint(6, 9, size=len(excluded_index))

# Now select 2 more students (excluding Excluded) to get 4–5 failed subjects
eligible_for_high_fail = failed_nonit_indices.difference(excluded_index)

# Select 2 more randomly to total 7 students failing >3 subjects
more_than_3_indices = np.random.choice(eligible_for_high_fail, size=2, replace=False)
nonit_df.loc[more_than_3_indices, 'failed_subjects'] = np.random.randint(4, 6, size=2)

# STEP 5: Remaining Non IT failed students — distribute 1–2 failed subjects
remaining_failed = eligible_for_high_fail.difference(more_than_3_indices)

# 39 failed students remaining
# Randomly split into two groups for 1 and 2 failed subjects
n_remain = len(remaining_failed)  # 31
half = n_remain // 2 # 15 or 16

remaining_failed = list(remaining_failed)
np.random.shuffle(remaining_failed)

low_1_fail = remaining_failed[:half]
low_2_fail = remaining_failed[half:]

# Assign 1s and 2s
nonit_df.loc[low_1_fail, 'failed_subjects'] = 1
nonit_df.loc[low_2_fail, 'failed_subjects'] = 2

In [41]:
# Update the failed_subjects column in the main data frame df
df.loc[nonit_df.index, 'failed_subjects'] = nonit_df['failed_subjects']

In [42]:
# Check only the Non IT students
nonit_students = df.loc[nonit_indices]

# 1. Total Non IT students who failed (not Satisfactory)
nonit_failed = nonit_students[nonit_students['academic_status'] != 'Satisfactory']

# 2. Total with non-zero failed_subjects
non_zero_fails = nonit_failed[nonit_failed['failed_subjects'] > 0]
print("Total assigned failed_subjects to Non IT failed students:", len(non_zero_fails))  # 46

# 3. Number of students with >3 failed subjects
gt3 = non_zero_fails[non_zero_fails['failed_subjects'] > 3]
print("Number with >3 failed subjects:", len(gt3))  # 10

# 4. Number with <=3 failed subjects
lte3 = non_zero_fails[non_zero_fails['failed_subjects'] <= 3]
print("Number with <=3 failed subjects:", len(lte3))  # 21

# 5. Print failed_subjects distribution (should show a variety like 1, 2, 4, etc.)
print("\nFailed Subjects Distribution:")
print(non_zero_fails['failed_subjects'].value_counts().sort_index())

# 6. Confirm no failed_subjects assigned to Satisfactory students
sat_students = nonit_students[nonit_students['academic_status'] == 'Satisfactory']
sats_with_fails = sat_students[sat_students['failed_subjects'] != 0]
print("\nSatisfactory students incorrectly assigned fails:", len(sats_with_fails))  # 0

Total assigned failed_subjects to Non IT failed students: 46
Number with >3 failed subjects: 7
Number with <=3 failed subjects: 39

Failed Subjects Distribution:
failed_subjects
1.0    19
2.0    20
5.0     2
6.0     3
7.0     1
8.0     1
Name: count, dtype: int64

Satisfactory students incorrectly assigned fails: 0

In [43]:
df['academic_status'].value_counts()

academic_status
Satisfactory        621
Conditional          42
Academic Caution     29
Excluded              6
Name: count, dtype: int64

In [44]:
df['identified_issues'].value_counts()

identified_issues
Late Enrollment         152
Mental health           144
Sickness                139
Poor time management    132
Death in family         131
Name: count, dtype: int64

In [45]:
df['student_cohort'].value_counts()

student_cohort
Return to Study    101
First year          93
Transferred         92
Continuing          89
Excluded            86
LOA                 85
New                 78
SRI to JCUB         74
Name: count, dtype: int64

###### Balance identified issues

In [46]:
# Count how many 'New' students had 'Late Enrollment' as an identified issue
df[(df['student_cohort'] == 'New') & (df['identified_issues'] == 'Late Enrollment')].shape

(23, 39)

In [47]:
# Reassign identified issues for New students

new_late_enrollment_indices = df[(df['student_cohort'] == 'New') & (df['identified_issues'] == 'Late Enrollment')].index

# Randomly choose indices to replace

reassign_identified_issue = np.random.choice(new_late_enrollment_indices, size = len(new_late_enrollment_indices)-20, replace=False)
df.loc[reassign_identified_issue, 'identified_issues'] = 'None'

In [48]:
df[(df['student_cohort'] == 'New') & (df['identified_issues'] == 'Late Enrollment')].shape

(20, 39)

In [49]:
df[(df['student_cohort'] != 'New')  & (df['academic_status'] == 'Satisfactory')].shape

(543, 39)

In [50]:
# Reassign identified issues for Satisfactory Students students

satisfactory_identified_issues_indices = df[(df['student_cohort'] != 'New')  & (df['academic_status'] == 'Satisfactory')].index

# Randomly choose indices to replace
# 80% of students with academic status Satisfactory (Not new)
reassign_identified_issue = np.random.choice(satisfactory_identified_issues_indices, size = 434, replace=False)
df.loc[reassign_identified_issue, 'identified_issues'] = 'None'

In [51]:
df[(df['student_cohort'] != 'New')  & (df['academic_status'] == 'Satisfactory') & (df['identified_issues'] == 'None')].shape

(434, 39)

In [52]:
df['identified_issues'].value_counts()

identified_issues
None                    437
Sickness                 56
Late Enrollment          56
Poor time management     52
Mental health            49
Death in family          48
Name: count, dtype: int64

###### Clean study skills column

In [53]:
df['study_skills(attended)'].value_counts()

study_skills(attended)
Referencing                     140
Writing                         125
Studiocity                      117
Essential Skills                113
Essential Skills and Reading    108
4R Essential Skills              95
Name: count, dtype: int64

In [54]:
# Only for first year and new students
study_skills_index = df[~df['student_cohort'].isin(['New', 'First year'])].index
reassign_study_skills = np.random.choice(study_skills_index, size = len(study_skills_index), replace=False)
df.loc[reassign_study_skills, 'study_skills(attended)'] = 'None'
df['study_skills(attended)'].value_counts()

study_skills(attended)
None                            527
Writing                          34
Studiocity                       33
Essential Skills                 29
Referencing                      28
Essential Skills and Reading     26
4R Essential Skills              21
Name: count, dtype: int64

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 698 entries, 0 to 697
Data columns (total 39 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   student_id                    698 non-null    int64
 1   course                        698 non-null    object
 2   student_cohort                698 non-null    object
 3   academic_status               698 non-null    object
 4   failed_subjects               698 non-null    float64
 5   study_skills(attended)        698 non-null    object
 6   referral                      698 non-null    object
 7   pp_meeting                    698 non-null    object
 8   self_assessment               698 non-null    object
 9   readiness_assessment_results  698 non-null    object
 10  follow_up                     698 non-null    object
 11  follow_up_type                698 non-null    object
 12  subject_1                     698 non-null    object
 13  subject_1_assess_1            698 non-null    float64
 14  subject_1_assess_2            698 non-null    float64
 15  subject_1_assess_3            698 non-null    float64
 16  subject_1_assess_4            698 non-null    float64
 17  attendance_1                  698 non-null    int64
 18  learn_jcu_issues_1            698 non-null    object
 19  lecturer_referral_1           698 non-null    object
 20  subject_2                     698 non-null    object
 21  subject_2_assess_1            698 non-null    float64
 22  subject_2_assess_2            698 non-null    float64
 23  subject_2_assess_3            698 non-null    float64
 24  subject_2_assess_4            698 non-null    float64
 25  attendance_2                  698 non-null    int64
 26  learn_jcu_issues_2            698 non-null    object
 27  lecturer_referral_2           698 non-null    object
 28  subject_3                     698 non-null    object
 29  subject_3_assess_1            698 non-null    float64
 30  subject_3_assess_2            698 non-null    float64
 31  subject_3_assess_3            698 non-null    float64
 32  subject_3_assess_4            698 non-null    float64
 33  attendance_3                  698 non-null    int64
 34  learn_jcu_issues_3            698 non-null    object
 35  lecturer_referral_3           698 non-null    object
 36  comments                      698 non-null    object
 37  identified_issues             698 non-null    object
 38  course_group                  698 non-null    object
dtypes: float64(13), int64(4), object(22)
memory usage: 212.8+ KB

###### Clean Attendance Data
This section prepares the attendance data for analysis by handling missing values, correcting inconsistencies, and ensuring all attendance records are valid and comparable.

In [56]:
# Parameters
MIN_ATTD_ASSIGN = 53   # Minimum attendance to assign (just above threshold)
MAX_ATTD_ASSIGN = 100  # Maximum attendance to assign (100%)

In [57]:
df['attendance_1'].describe()

count    698.000000
mean      51.173352
std       29.311125
min        0.000000
25%       26.000000
50%       52.000000
75%       77.000000
max      100.000000
Name: attendance_1, dtype: float64

In [58]:
df['academic_status'].value_counts()

academic_status
Satisfactory        621
Conditional          42
Academic Caution     29
Excluded              6
Name: count, dtype: int64

In [59]:
# Check for students with attendance less than 52%
all_low_attendance = df[df['attendance_1'] <= 52]

# Satisfactory attendance
satisfactory_low_52 = len(all_low_attendance[all_low_attendance['academic_status'] == 'Satisfactory'])

# Non-Satisfactory attendance
non_satisfactory_low_52 = len(all_low_attendance[all_low_attendance['academic_status'] != 'Satisfactory'])

print(satisfactory_low_52, non_satisfactory_low_52)
print(satisfactory_low_52 + non_satisfactory_low_52, "should equal", len(all_low_attendance))

313 44
357 should equal 357

In [60]:
# First year with attendance less than 52%
first_year_low_52 = len(all_low_attendance[all_low_attendance['student_cohort']=='First year'])
first_year_low_52

49

In [61]:
# New students with attendance less than 52%
new_low_52 = len(all_low_attendance[all_low_attendance['student_cohort']=='New'])
new_low_52

38

In [62]:
# Remaining student cohorts with less than 52%
mask = ~all_low_attendance['student_cohort'].isin(['New', 'First year'])
std_less_52 = len(all_low_attendance[mask])
std_less_52

270

In [63]:
# Get first year students with academic status 'Satisfactory' and attendance less than 52
df[(df['student_cohort']== 'First year') & (df['academic_status']=='Satisfactory') & (df['attendance_1']<=52)].shape

(45, 39)

In [64]:
df[(df['student_cohort']== 'First year') & (df['academic_status']=='Satisfactory')].shape

(78, 39)

In [65]:
df[(df['student_cohort']== 'First year') & (df['academic_status']!='Satisfactory')].shape

(15, 39)

In [66]:
# Get index of first year students with academic status 'Satisfactory' and attendance less than 52

first_year_satisfactory = df[(df['student_cohort']== 'First year') & (df['academic_status']=='Satisfactory') & (df['attendance_1']<=52)]
first_year_index = first_year_satisfactory.index

# Change the attendance of 30% first year students to more than 52%
n_assign = 38 # Maximum number of students to assign higher attendance

# Draw random sample of up to n_assign students
n_select = min(n_assign, len(first_year_index))
random_assign_attendance = np.random.choice(first_year_index, size = n_assign, replace = False)
df.loc[random_assign_attendance, 'attendance_1'] = np.random.uniform(MIN_ATTD_ASSIGN, MAX_ATTD_ASSIGN, size=n_select)

/tmp/ipykernel_83451/2375422476.py:12: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[73.00359809 66.90932036 72.52704847 99.94109939 99.80283668 59.37088158
 75.86584245 73.21221076 90.08361187 66.75681632 91.10558205 98.31897369
 90.85440257 84.63624406 80.05475644 88.98220878 83.64769718 71.40461611
 86.09105257 62.28573659 73.8943762  76.21620439 92.65947411 85.36625603
 82.08116031 67.2530342  85.95369955 67.46359454 89.86285493 81.80672544
 88.20868932 89.32800197 93.93451249 67.40310494 76.19436173 90.30452994
 69.28023019 71.60580515]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[random_assign_attendance, 'attendance_1'] = np.random.uniform(MIN_ATTD_ASSIGN, MAX_ATTD_ASSIGN, size=n_select)

In [67]:
df[(df['student_cohort']== 'First year') & (df['academic_status']=='Satisfactory') & (df['attendance_1']<=52)].shape

(7, 39)

In [68]:
first_year_non_satisfactory= df[(df['student_cohort']== 'First year') & (df['academic_status']!='Satisfactory') & (df['attendance_1']<=52)]
first_year_non_satisfactory.shape
first_year_non_satisfactory= df[(df['student_cohort']== 'First year') & (df['academic_status']!='Satisfactory') & (df['attendance_1']>52)]
first_year_non_satisfactory.shape

(11, 39)

In [69]:
df[(df['student_cohort']== 'New') & (df['academic_status']=='Satisfactory') & (df['attendance_1']<=52)].shape

(38, 39)

In [70]:
df[(df['student_cohort']== 'New') & (df['academic_status']!='Satisfactory') & (df['attendance_1']<=52)].shape

(0, 39)

In [71]:
df[df['student_cohort']=='New']['academic_status'].value_counts()

academic_status
Satisfactory    78
Name: count, dtype: int64

In [72]:
# Get index of New students with academic status 'Satisfactory'

new_satisfactory = df[(df['student_cohort']=='New') & (df['academic_status']=='Satisfactory') & (df['attendance_1']<=52)]
new_index = new_satisfactory.index

# Change the attendance of 10 New students to more than 52%
n_assign = 27 # Maximum number of students to assign higher attendance

# Draw random sample of up to n_assign students
n_select = min(n_assign, len(new_index))
random_assign_attendance = np.random.choice(new_index, size = n_assign, replace = False)
df.loc[random_assign_attendance, 'attendance_1'] = np.random.uniform(MIN_ATTD_ASSIGN, MAX_ATTD_ASSIGN, size=n_select)

In [73]:
df[(df['student_cohort']=='New') & (df['attendance_1']<=52) & (df['academic_status']=='Satisfactory')].shape

(11, 39)

In [74]:
df[(~df['student_cohort'].isin(['First year', 'New'])) & (df['academic_status'] == 'Satisfactory') & (df['attendance_1'] <= 52)].shape

(230, 39)

In [75]:
# Get index of students with academic status 'Satisfactory'

stds_satisfactory = df[(~df['student_cohort'].isin(['First year', 'New'])) & (df['academic_status'] == 'Satisfactory') & (df['attendance_1'] <= 52)]
stds_satisfactory_index = stds_satisfactory.index

# Change the attendance of 3 New students to more than 52%
n_assign = 226 # Maximum number of students to assign higher attendance

# Draw random sample of up to n_assign students
n_select = min(n_assign, len(stds_satisfactory_index))
random_assign_attendance = np.random.choice(stds_satisfactory_index, size = n_assign, replace = False)
df.loc[random_assign_attendance, 'attendance_1'] = np.random.uniform(MIN_ATTD_ASSIGN, MAX_ATTD_ASSIGN, size=n_select)

In [76]:
df[(~df['student_cohort'].isin(['First year', 'New'])) & (df['academic_status'] == 'Satisfactory') & (df['attendance_1'] <= 52)].shape

(4, 39)

In [77]:
df[(~df['student_cohort'].isin(['First year', 'New'])) & (df['academic_status'] != 'Satisfactory') & (df['attendance_1'] <= 52)].shape

(40, 39)

In [78]:
# Get index of students with academic status 'Satisfactory'

stds_non_satisfactory = df[(~df['student_cohort'].isin(['First year', 'New'])) & (df['academic_status'] != 'Satisfactory') & (df['attendance_1'] <= 52)]
stds_non_satisfactory_index = stds_non_satisfactory.index

# Change the attendance of 3 New students to more than 52%
n_assign = 25# Maximum number of students to assign higher attendance

# Draw random sample of up to n_assign students
n_select = min(n_assign, len(stds_non_satisfactory_index))
random_assign_attendance = np.random.choice(stds_non_satisfactory_index, size = n_assign, replace = False)
df.loc[random_assign_attendance, 'attendance_1'] = np.random.uniform(MIN_ATTD_ASSIGN, MAX_ATTD_ASSIGN, size=n_select)

In [79]:
df[(~df['student_cohort'].isin(['First year', 'New'])) & (df['academic_status'] != 'Satisfactory') & (df['attendance_1'] <= 52)].shape

(15, 39)

In [80]:
df['attendance_1'].describe()

count    698.000000
mean      73.424516
std       18.402734
min        0.000000
25%       63.000000
50%       75.693306
75%       87.034211
max      100.000000
Name: attendance_1, dtype: float64

In [81]:
df['attendance_adj'] = df['attendance_1'] - 4.76
df['attendance_adj'] = df['attendance_adj'].clip(lower=0, upper=100)  # Stay within 0–100%
df['attendance_1'] = df['attendance_adj']

In [82]:
df['attendance_1'].describe()

count    698.000000
mean      68.694717
std       18.286831
min        0.000000
25%       58.240000
50%       70.933306
75%       82.274211
max       95.240000
Name: attendance_1, dtype: float64

In [83]:
df['attendance_2'].describe()

count    698.000000
mean      49.723496
std       28.779966
min        0.000000
25%       26.000000
50%       48.000000
75%       74.750000
max      100.000000
Name: attendance_2, dtype: float64

In [84]:
df['attendance_3'].describe()

count    698.000000
mean      49.939828
std       29.299558
min        0.000000
25%       26.000000
50%       49.000000
75%       75.000000
max      100.000000
Name: attendance_3, dtype: float64

In [85]:
# Parameters
std_extra = 8  # How much each subject can differ from the base
low = 30        # Minimum reasonable attendance
high = 100      # Maximum possible attendance

# Generate random differences for each new attendance column
df['attendance_2'] = np.clip(df['attendance_1'] + np.random.normal(0, std_extra, len(df)), low, high)
df['attendance_3'] = np.clip(df['attendance_1'] + np.random.normal(0, std_extra, len(df)), low, high)

In [86]:
df['attendance_2'].describe()

count    698.000000
mean      69.578726
std       17.519817
min       30.000000
25%       57.589140
50%       70.218372
75%       82.595280
max      100.000000
Name: attendance_2, dtype: float64

In [87]:
df['attendance_3'].describe()

count    698.000000
mean      69.554953
std       17.678307
min       30.000000
25%       57.376981
50%       70.536398
75%       83.433836
max      100.000000
Name: attendance_3, dtype: float64

###### Clean Subject Assessment score

In [88]:
df['referral'].value_counts()

referral
Other                 148
Student Counsellor    144
Enrollment            138
Student Advocate      137
Lecturer              131
Name: count, dtype: int64

In [89]:
df.head(20)

,student_id,course,student_cohort,academic_status,failed_subjects,study_skills(attended),referral,pp_meeting,self_assessment,readiness_assessment_results,follow_up,follow_up_type,subject_1,subject_1_assess_1,subject_1_assess_2,subject_1_assess_3,subject_1_assess_4,attendance_1,learn_jcu_issues_1,lecturer_referral_1,subject_2,subject_2_assess_1,subject_2_assess_2,subject_2_assess_3,subject_2_assess_4,attendance_2,learn_jcu_issues_2,lecturer_referral_2,subject_3,subject_3_assess_1,subject_3_assess_2,subject_3_assess_3,subject_3_assess_4,attendance_3,learn_jcu_issues_3,lecturer_referral_3,comments,identified_issues,course_group,attendance_adj
0,159,master of education - master of business admin...,First year,Satisfactory,0.0,Referencing,Other,Not relevant,No,L/G:9/10 N:5/10 R:8/10,No,Email,ED5097,76.20,69.23,47.21,26.64,58.240000,No Access,Non Submission,ED5880,34.93,7.79,1.84,47.12,56.824219,No Access,Non Submission,LB5113,31.30,26.76,5.73,10.20,62.764846,No Access,Non Submission,Week 7. Student disclosed high stress levels a...,Sickness,Non-IT,58.240000
1,500,master of professional accounting,LOA,Satisfactory,0.0,None,Student Advocate,Not relevant,No,L/G:9/10 N:5/10 R:8/10,No,No Reply,CO5117,37.87,91.51,51.98,1.72,73.240000,Access,Attendance,CO5103,35.19,73.64,20.57,4.89,79.613215,Access,Non Submission,CO5109,31.31,42.75,31.73,21.51,60.665913,No Access,Non Submission,Week 7. Student disclosed high stress levels a...,None,Non-IT,73.240000
2,397,master of engineering management,First year,Satisfactory,0.0,Essential Skills and Reading,Student Counsellor,Booked,Yes,L/G:9/10 N:5/10 R:8/10,No,F2F,EG5200,5.32,76.72,30.64,16.11,79.876244,No Access,Non Submission,EG5220,83.34,75.41,98.96,38.26,79.128785,No Access,Concern for Welfare,EG5310,86.01,10.06,66.54,56.42,75.634785,Access,Attendance,booked to see a doctor. Week 5. Student contac...,None,Non-IT,79.876244
3,156,master of education - master of business admin...,SRI to JCUB,Satisfactory,0.0,None,Enrollment,Booked,Yes,L/G:9/10 N:5/10 R:8/10,Yes,Phone,ED5097,8.10,11.63,16.89,31.49,54.240000,Access,Concern for Welfare,ED5880,65.71,65.08,12.75,71.78,64.407183,No Access,Attendance,LB5113,12.92,41.46,56.79,41.28,63.039358,Access,Non Submission,Week 6. Student submitted assessment late. Ext...,None,Non-IT,54.240000
4,322,bachelor of business,First year,Satisfactory,0.0,Referencing,Student Counsellor,Attended,No,L/G:9/10 N:5/10 R:8/10,No,Email,BU1002,59.06,58.49,97.55,85.08,57.525737,Access,Concern for Welfare,BU1003,97.54,56.75,68.86,92.77,76.411337,No Access,Concern for Welfare,BU1007,44.47,5.80,42.48,77.04,48.463685,Access,Concern for Welfare,Week 4. Student submitted first assessment lat...,None,Non-IT,57.525737
5,213,master of information technology,Return to Study,Satisfactory,0.0,None,Enrollment,Attended,No,L/G:9/10 N:5/10 R:8/10,No,Email,CP5046,13.88,65.32,81.75,74.10,80.041271,No Access,Concern for Welfare,CP5047,95.11,52.08,94.94,25.39,86.969012,Access,Concern for Welfare,CP5503,2.93,49.50,63.95,86.65,69.929117,Access,Concern for Welfare,Week 7. Student disclosed high stress levels a...,None,IT,80.041271
6,235,master of information technology,Return to Study,Satisfactory,0.0,None,Student Advocate,Attended,No,L/G:9/10 N:5/10 R:8/10,Yes,No Reply,CP5046,11.12,50.38,37.04,75.09,94.240000,No Access,Attendance,CP5047,5.17,51.40,38.92,31.78,98.670858,Access,Attendance,CP5503,68.53,60.09,92.08,91.18,87.152225,Access,Non Submission,Week 6. Student submitted assessment late. Ext...,Mental health,IT,94.240000
7,290,bachelor of business,First year,Satisfactory,0.0,Writing,Lecturer,Booked,Yes,L/G:9/10 N:5/10 R:8/10,No,F2F,BU1002,88.04,19.33,57.49,4.06,68.452211,Access,Attendance,BU1003,31.99,93.06,65.60,88.87,68.243081,No Access,Concern for Welfare,BU1007,91.76,44.03,10.88,69.10,61.936037,Access,Concern for Welfare,Week 5. Low engagement in tutorials. Follow-up...,Poor time management,Non-IT,68.452211
8,301,bachelor of business,Excluded,Satisfactory,0.0,None,Lecturer,Not relevant,Yes,L/G:9/10 N:5/10 R:8/10,No,Phone,BU1002,49.41,37.01,2.69,48.09,87.240000,Access,Attendance,BU1003,52.30,12.26,38.18,27.88,79.587088,Access,Attendance,BU1007,48.63,60.87,94.75,75.73,87.987822,Access,Attendance,Week 7. Missed second assessment. Student cont...,Poor time management,Non-IT,87.240000
9,357,master of engineering management,Transferred,Satisfactory,0.0,None,Other,Attended,Yes,L/G:9/10 N:5/10 R:8/10,No,Email,EG5200,5.06,56.80,92.39,0.29,72.240000,No Access,Attendance,EG5220,63.18,75.22,99.65,94.63,61.856053,No Access,Concern for Welfare,EG5310,16.82,31.99,99.32,17.39,79.399494,Access,Non Submission,booked to see a doctor. Week 5. Student contac...,None,Non-IT,72.240000
10,672,master of data science (professional),New,Satisfactory,0.0,Essential Skills and Reading,Other,Not relevant,Yes,L/G:9/10 N:5/10 R:8/10,No,F2F,MA5831,2.09,90.53,89.91,88.33,92.240000,Access,Non Submission,MA5840,90.98,90.52,52.03,84.66,87.719620,Access,Attendance,MA5851,66.82,88.60,29.88,97.46,90.674357,No Access,Attendance,Week 5. Low engagement in tutorials. Follow-up...,Death in family,IT,92.240000
11,329,bachelor of business,LOA,Satisfactory,0.0,None,Student Counsellor,Booked,No,L/G:9/10 N:5/10 R:8/10,Yes,Phone,BU1002,21.89,19.45,73.73,97.78,78.658224,Access,Non Submission,BU1003,35.41,98.39,78.30,89.90,78.272640,Access,Concern for Welfare,BU1007,94.39,74.14,1.73,37.22,77.950248,Access,Non Submission,booked to see a doctor. Week 5. Student contac...,None,Non-IT,78.658224
12,200,master of information technology,Continuing,Satisfactory,0.0,None,Enrollment,Rescheduled,No,L/G:9/10 N:5/10 R:8/10,Yes,F2F,CP5046,9.61,76.93,45.67,31.27,93.240000,Access,Concern for Welfare,CP5047,74.24,72.72,64.31,48.31,86.178743,No Access,Concern for Welfare,CP5503,8.05,59.74,17.69,14.78,100.000000,Access,Concern for Welfare,Week 8. Student re-engaged with tutorials. Sub...,None,IT,93.240000
13,79,master of business administration,Excluded,Satisfactory,0.0,None,Lecturer,Booked,Yes,L/G:9/10 N:5/10 R:8/10,No,Phone,LB5113,56.07,56.82,92.73,56.89,66.403371,No Access,Attendance,LB5202,88.19,32.73,2.42,28.90,66.647659,Access,Attendance,LB5205,84.29,43.41,93.53,76.50,62.242785,Access,Non Submission,Week 5. Student absent from multiple classes. ...,None,Non-IT,66.403371
14,598,"bachelor of tourism, hospitality and events",Transferred,Satisfactory,0.0,None,Student Counsellor,Not relevant,No,L/G:9/10 N:5/10 R:8/10,No,Email,TO1008,13.85,22.58,35.56,74.82,60.240000,Access,Concern for Welfare,TO2117,32.40,56.23,92.12,89.55,66.120474,Access,Attendance,TO3052,35.54,12.68,48.45,14.45,61.636697,Access,Non Submission,Week 6. Student reported working long hours. R...,None,Non-IT,60.240000
15,570,master of international tourism and hospitalit...,First year,Satisfactory,0.0,Essential Skills and Reading,Other,Booked,Yes,L/G:9/10 N:5/10 R:8/10,Yes,Email,TO5101,16.20,68.72,8.73,63.19,91.240000,Access,Non Submission,TO5103,57.73,56.38,37.97,50.01,82.476362,Access,Concern for Welfare,TO5104,61.48,52.23,82.78,90.49,89.253749,Access,Concern for Welfare,Week 6. Student submitted assessment late. Ext...,None,Non-IT,91.240000
16,447,bachelor of information technology,First year,Satisfactory,0.0,Studiocity,Student Counsellor,Not relevant,No,L/G:9/10 N:5/10 R:8/10,Yes,No Reply,CP1401,89.54,72.47,92.27,46.72,74.240000,Access,Attendance,CP1402,97.83,80.77,96.38,11.16,65.740188,Access,Concern for Welfare,CP1404,26.30,98.62,37.57,66.79,89.551232,Access,Non Submission,booked to see a doctor. Week 5. Student contac...,None,IT,74.240000
17,507,master of professional accounting,First year,Satisfactory,0.0,Studiocity,Student Counsellor,Booked,No,L/G:9/10 N:5/10 R:8/10,Yes,F2F,CO5117,85.12,81.94,26.95,23.98,89.174512,Access,Non Submission,CO5103,51.04,46.87,11.72,38.36,100.000000,Access,Non Submission,CO5109,45.79,80.75,53.04,99.04,93.066827,Access,Non Submission,Week 5. Student absent from multiple classes. ...,None,Non-IT,89.174512
18,626,bachelor of commerce,Return to Study,Satisfactory,0.0,None,Other,Rescheduled,Yes,L/G:9/10 N:5/10 R:8/10,Yes,No Reply,BU1112,79.83,3.43,50.04,33.35,50.046770,Access,Non Submission,BX2011,65.67,49.02,39.95,69.18,53.496385,Access,Attendance,BX2014,21.45,5.16,46.86,43.83,50.426468,Access,Attendance,Week 5. Low engagement in tutorials. Follow-up...,None,Non-IT,50.046770
19,603,master of professional accounting - master of ...,LOA,Satisfactory,0.0,None,Student Advocate,Rescheduled,Yes,L/G:9/10 N:5/10 R:8/10,Yes,Email,CO5117,42.38,6.39,15.05,91.71,62.613217,Access,Concern for Welfare,CO5103,41.51,44.72,37.94,28.55,57.642015,Access,Non Submission,LB5113,75.42,37.01,19.21,1.44,73.257755,No Access,Attendance,Week 5. Student absent from multiple classes. ...,None,Non-IT,62.613217

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 698 entries, 0 to 697
Data columns (total 40 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   student_id                    698 non-null    int64
 1   course                        698 non-null    object
 2   student_cohort                698 non-null    object
 3   academic_status               698 non-null    object
 4   failed_subjects               698 non-null    float64
 5   study_skills(attended)        698 non-null    object
 6   referral                      698 non-null    object
 7   pp_meeting                    698 non-null    object
 8   self_assessment               698 non-null    object
 9   readiness_assessment_results  698 non-null    object
 10  follow_up                     698 non-null    object
 11  follow_up_type                698 non-null    object
 12  subject_1                     698 non-null    object
 13  subject_1_assess_1            698 non-null    float64
 14  subject_1_assess_2            698 non-null    float64
 15  subject_1_assess_3            698 non-null    float64
 16  subject_1_assess_4            698 non-null    float64
 17  attendance_1                  698 non-null    float64
 18  learn_jcu_issues_1            698 non-null    object
 19  lecturer_referral_1           698 non-null    object
 20  subject_2                     698 non-null    object
 21  subject_2_assess_1            698 non-null    float64
 22  subject_2_assess_2            698 non-null    float64
 23  subject_2_assess_3            698 non-null    float64
 24  subject_2_assess_4            698 non-null    float64
 25  attendance_2                  698 non-null    float64
 26  learn_jcu_issues_2            698 non-null    object
 27  lecturer_referral_2           698 non-null    object
 28  subject_3                     698 non-null    object
 29  subject_3_assess_1            698 non-null    float64
 30  subject_3_assess_2            698 non-null    float64
 31  subject_3_assess_3            698 non-null    float64
 32  subject_3_assess_4            698 non-null    float64
 33  attendance_3                  698 non-null    float64
 34  learn_jcu_issues_3            698 non-null    object
 35  lecturer_referral_3           698 non-null    object
 36  comments                      698 non-null    object
 37  identified_issues             698 non-null    object
 38  course_group                  698 non-null    object
 39  attendance_adj                698 non-null    float64
dtypes: float64(17), int64(1), object(22)
memory usage: 218.3+ KB

In [91]:
df.to_csv('jcu_student_cleaned.csv', index=False)
print("DataFrame exported to jcu_student_cleaned.csv")
print(f"Shape: {df.shape}")
print(f"Columns: {list(df.columns)}")

DataFrame exported to jcu_student_cleaned.csv
Shape: (698, 40)
Columns: ['student_id', 'course', 'student_cohort', 'academic_status', 'failed_subjects', 'study_skills(attended)', 'referral', 'pp_meeting', 'self_assessment', 'readiness_assessment_results', 'follow_up', 'follow_up_type', 'subject_1', 'subject_1_assess_1', 'subject_1_assess_2', 'subject_1_assess_3', 'subject_1_assess_4', 'attendance_1', 'learn_jcu_issues_1', 'lecturer_referral_1', 'subject_2', 'subject_2_assess_1', 'subject_2_assess_2', 'subject_2_assess_3', 'subject_2_assess_4', 'attendance_2', 'learn_jcu_issues_2', 'lecturer_referral_2', 'subject_3', 'subject_3_assess_1', 'subject_3_assess_2', 'subject_3_assess_3', 'subject_3_assess_4', 'attendance_3', 'learn_jcu_issues_3', 'lecturer_referral_3', 'comments', 'identified_issues', 'course_group', 'attendance_adj']